name: Publish to S3

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          node_version: 20.x

      - name: Test
        run: pnpm run test

      - name: Configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Configure AWS credentials, you can define it in the repository secrets.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync dist folder to S3
        if: success()
        # This is a sample command to sync the dist folder to S3 bucket, you can change it to your own command.
        run: |
          aws s3 sync dist s3://your-s3-bucket-name --delete
